### ISSUE TITLE
Does training image size matter?

### ISSUE THREAD

**Issue by AdamWP** [TensorBox/TensorBox#175]
I'm about to annotate a new data set and was wondering if there is any benefit to training on high resolution images rather than low resolution.  I understand that it will take longer to train on larger images and that the dimensions must be a multiple of 32.   My current image set is 1440x1920.  Would I be better off resizing to 480x640, or is bigger better?

**Comment by chuckbasstan123** [comment]
For testing
[evaluate.py](https://github.com/TensorBox/TensorBox/blob/master/evaluate.py)
At line 44&45 
"orig_img = imread('%s/%s' % (data_dir, true_anno.imageName))[:,:,:3]
img = imresize(orig_img, (H["image_height"], H["image_width"]), interp='cubic')"

[train_ultils](https://github.com/TensorBox/TensorBox/blob/master/utils/train_utils.py)
line 52, they also used imresize
 "I = imresize(I, (H["image_height"], H["image_width"]), interp='cubic')"

So I think it doesn't matter you resize the image or not, the script will resize your images and annotation automatically.

**Comment by AdamWP** [comment]
It turns out that smaller images worked out better, at least with my experiments.  High resolution isn't required to identify most object.
