### ISSUE TITLE
Confidences

### ISSUE THREAD

**Issue by mkreich** [TensorBox/TensorBox#181]
I am using tensorbox for an app and therefore I need to reimplement `add_rectangles` from `train_utils.py` in Java.
I was wondering why only half of the confidences were used and only the last of the two ones:

`conf = np.max(confidences_r[0, y, x, n, 1:]`
where `confidences_r.shape = (1, 15, 20, 1, 2)`

**Comment by Russell91** [comment]
The confidences are output from a softmax, which produces a probability distribution. Thus, if the first half are "p", the other half are equal to "1 - p"
