### ISSUE TITLE
Cannot test evaluate.ipynb with images of size other than 480*640

### ISSUE THREAD

**Issue by arjungrylls** [TensorBox/TensorBox#182]
f.reset_default_graph()
x_in = tf.placeholder(tf.float32, name='x_in', shape=[480, 640, 3])
if H['use_rezoom']:
    pred_boxes, pred_logits, pred_confidences, pred_confs_deltas, pred_boxes_deltas = build_forward(H, tf.expand_dims(x_in, 0), 'test', reuse=None)
    grid_area = H['grid_height'] * H['grid_width']
    pred_confidences = tf.reshape(tf.nn.softmax(tf.reshape(pred_confs_deltas, [grid_area * H['rnn_len'], 2])), [grid_area, H['rnn_len'], 2])
    if H['reregress']:
        pred_boxes = pred_boxes + pred_boxes_deltas
else:
    pred_boxes, pred_logits, pred_confidences = build_forward(H, tf.expand_dims(x_in, 0), 'test', reuse=None)
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    saver.restore(sess, './data/overfeat_rezoom/save.ckpt-%dv2' % iteration)

    annolist = al.AnnoList()
    import time; t = time.time()
    for i in range(0, 500):
        true_anno = true_annos[i]
        img = imread('./data/%s' % true_anno.imageName)
        feed = {x_in: img}
        (np_pred_boxes, np_pred_confidences) = sess.run([pred_boxes, pred_confidences], feed_dict=feed)
        pred_anno = al.Annotation()
        pred_anno.imageName = true_anno.imageName
        new_img, rects = add_rectangles(H, [img], np_pred_confidences, np_pred_boxes,
                                        use_stitching=True, rnn_len=H['rnn_len'], min_conf=0.7,
                                        show_suppressed=False)
    
        pred_anno.rects = rects
        annolist.append(pred_anno)

        if i % 10 == 0 and i < 200:
            pass
            fig = plt.figure(figsize=(12, 12))
            plt.imshow(new_img)
        if i % 100 == 0:
            print(i)
    avg_time = (time.time() - t) / (i + 1)
 print('%f images/sec' % (1. / avg_time))

WARNING:tensorflow:From <ipython-input-12-31faa5f22b5d>:13 in <module>.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-31faa5f22b5d> in <module>()
     20         img = imread('./data/%s' % true_anno.imageName)
     21         feed = {x_in: img}
---> 22         (np_pred_boxes, np_pred_confidences) = sess.run([pred_boxes, pred_confidences], feed_dict=feed)
     23         pred_anno = al.Annotation()
     24         pred_anno.imageName = true_anno.imageName

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    764     try:
    765       result = self._run(None, fetches, feed_dict, options_ptr,
--> 766                          run_metadata_ptr)
    767       if run_metadata:
    768         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    941                 'Cannot feed value of shape %r for Tensor %r, '
    942                 'which has shape %r'
--> 943                 % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
    944           if not self.graph.is_feedable(subfeed_t):
    945             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (3264, 2448, 3) for Tensor u'x_in:0', which has shape '(480, 640, 3)'

**Comment by twhitloc** [comment]
Hi Arjun,

As far as I am aware this cannot be done because the expected numpy array is of dimensions 480 x 640 x 3.  You would have two options, one being training a new model with the dimensions 3264 x 2448 coded in the hypes.json file (image_width, image_height).  The other would be to resize your image that you are trying to evaluate using imresize in the scipy.misc module.  This would attempt to convert the numpy array that represents the image into the expected dimensions
