### ISSUE TITLE
Box location is different from what I did

### ISSUE THREAD

**Issue by chi3236** [TensorBox/TensorBox#184]
I set box location with make_json.py, but box location is different my setting area.
For example,
![8_true](https://cloud.githubusercontent.com/assets/7023605/22730227/7362be2a-ee29-11e6-9c48-83bbe1317018.jpg)

I choose the cars and make the in the box, but boxes are located in wrong side when the train.py is doing validation.
What can I do?

**Comment by chi3236** [comment]
There are mistakes on img files. It's resolution must be unified

**Comment by BolongXIONG** [comment]
dear chi3236,  when i am using make_json.py to make boxes in the pics, and I always come across this problems:
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1813, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

Can you tell me how to use this make_json.py file?
I just follow the instruction in the file but i always get problems.
