### ISSUE TITLE
Evaluate.ipynb and save.ckpt 

### ISSUE THREAD

**Issue by Gagazet** [TensorBox/TensorBox#190]
Hey guys, have one more question. After traning model with brainwash, i have 3 save.ckpt files:
save.ckpt-20000.data
save.ckpt-20000.index
save.ckpt-20000.meta
 I tryed to use Evaluate.ipynb to open it, like at test file, but it's dosent work. What the file Russell91 using for it and how he made it? 
\\It's works with evaluate.py only 🌵 

# **_FOUND A MISTAKE, SORRY FOR STUPID QUESTION_**

**Comment by chabir** [comment]
@Gagazet, sorry to ask but how did you solve the problem ? I am having the same issue...

**Comment by Gagazet** [comment]
@chabir Hello, my friend. This 3 files it's full set of save.ckpt-20000 Just put them at one folder and wrote correct path to them at Evaluate.ipynb (path to the first part of name, before . ).
Be in touch~
