### ISSUE TITLE
error when setting "use_lstm": true in overfeat_rezoom.json

### ISSUE THREAD

**Issue by brisker** [TensorBox/TensorBox#228]
where is build_lstm_inner ` lstm_outputs = build_lstm_inner(H, lstm_input)`  defined? [it is use here](https://github.com/TensorBox/TensorBox/blob/master/train.py#L139), the code just tell me `build_lstm_inner  `is  not defined

**Comment by RomanSteinberg** [comment]
It is defined in `train.py` line 35. And it is properly works. How can `code` tell you something?

**Comment by brisker** [comment]
@RomanSteinberg 
I mean there is a build_lstm_inner function defined [here](https://github.com/TensorBox/TensorBox/blob/master/train.py#L139). But I can not find it in train.py

**Comment by brisker** [comment]
@RomanSteinberg 
Traceback (most recent call last):
  File "train.py", line 523, in <module>
    main()
  File "train.py", line 520, in main
    train(H, test_images=[])
  File "train.py", line 422, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 315, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 216, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, phase, reuse)
  File "train.py", line 138, in build_forward
    lstm_outputs = build_lstm_inner(H, lstm_input)
NameError: global name 'build_lstm_inner' is not defined

**Comment by RomanSteinberg** [comment]
@brisker the following line of code:
```lstm_outputs = build_lstm_inner(H, lstm_input)```
has number 168 in my `train.py`. So, I think you have to pull from repo.
